import type { BlogPost } from '@/types'

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'how-to-prepare-hvac-for-nj-winter',
    title: 'How to Prepare Your HVAC System for a New Jersey Winter',
    excerpt: 'Winter in NJ can be brutal. Here\'s how to make sure your heating system is ready before the first cold snap hits — and what to watch for that signals a problem.',
    date: '2025-11-01',
    category: 'Maintenance',
  },
  {
    slug: 'signs-ac-needs-repair',
    title: '7 Warning Signs Your AC Needs Repair Before Summer',
    excerpt: 'Don\'t wait until the hottest day of the year to discover your AC is failing. These 7 warning signs tell you it\'s time to call an HVAC technician now.',
    date: '2025-04-15',
    category: 'AC Repair',
  },
  {
    slug: 'heat-pump-vs-furnace-nj',
    title: 'Heat Pump vs. Furnace: What\'s Right for Your NJ Home?',
    excerpt: 'Both heat pumps and gas furnaces can heat your NJ home effectively — but which one saves more money? We break down the pros, cons, and costs for Northern NJ homeowners.',
    date: '2025-10-10',
    category: 'Buying Advice',
  },
  {
    slug: 'energy-saving-hvac-tips',
    title: '10 Easy Ways to Reduce Your HVAC Energy Bills in NJ',
    excerpt: 'Small changes can add up to big savings on your heating and cooling bills. These 10 tips are easy to implement and can reduce your energy costs by 15–30%.',
    date: '2025-09-05',
    category: 'Energy Savings',
  },
  {
    slug: 'when-to-replace-hvac-system',
    title: 'When Should You Replace Your HVAC System? A Complete Guide',
    excerpt: 'Is it time to repair or replace? This guide walks through all the factors — age, efficiency, repair cost, and more — to help you make the right decision.',
    date: '2025-08-20',
    category: 'Buying Advice',
  },
  {
    slug: 'ductless-mini-split-benefits',
    title: 'Why Ductless Mini-Splits Are Perfect for NJ Older Homes',
    excerpt: 'Many NJ homes were built without central HVAC ductwork. Ductless mini-splits offer a modern, efficient solution that works perfectly in these situations.',
    date: '2025-07-12',
    category: 'Mini-Splits',
  },
]

export const BLOG_CONTENT: Record<string, string[]> = {
  'how-to-prepare-hvac-for-nj-winter': [
    'New Jersey winters are no joke. Temperatures regularly drop into the teens, and a heating system failure at the wrong moment can mean frozen pipes, emergency service calls, and hundreds of dollars in avoidable repairs. The good news: a little preparation in the fall can prevent most winter HVAC emergencies.',
    'Start with a professional tune-up in September or October before demand peaks. A licensed technician will inspect your heat exchanger for cracks (critical for gas furnaces — a cracked exchanger can leak carbon monoxide), test ignition systems, check refrigerant levels on heat pumps, and verify that all safeties are working correctly.',
    'Replace your air filter before heating season begins. A clogged filter forces your system to work harder, reducing efficiency and potentially causing it to overheat and shut down. During peak heating months, check the filter monthly and replace it when it looks visibly dirty.',
    'Test your thermostat now, not when you first need heat. Turn the system to heating mode and verify it cycles on and produces warm air. If you have a smart thermostat, update the firmware and check the battery. If your thermostat is more than 10 years old, consider upgrading to a programmable model — it will pay for itself in energy savings.',
    'Inspect and clear all vents and registers throughout the house. Furniture placed over floor registers, closed vents in unused rooms, and blocked return-air grilles all reduce efficiency and can cause pressure imbalances that damage the system over time.',
    'Know your emergency contacts before you need them. Save Go Pro Heating & Cooling\'s number — 973-938-2217 — in your phone. We offer 24/7 emergency heating repair throughout Northern NJ with no overtime charges. Having the number ready means less downtime if your system fails on the coldest night of the year.',
  ],
  'signs-ac-needs-repair': [
    'Waiting until your AC completely fails before calling for service is the most expensive approach. Minor problems that cost a few hundred dollars to fix today can turn into major failures costing several times more if ignored. Here are the warning signs that tell you it\'s time to call.',
    'Warm or weak airflow is the most obvious sign something is wrong. If your AC is running but not cooling, or if airflow from the vents feels weak, you likely have a refrigerant leak, a failing compressor, or a dirty evaporator coil. All of these require professional service.',
    'Strange noises that weren\'t there before — banging, clanking, squealing, or grinding — indicate mechanical problems. A loose part, a failing motor bearing, or a bent fan blade can all cause unusual sounds. Running the system when it\'s making these noises often causes additional damage.',
    'Ice forming on the unit or refrigerant lines is counterintuitive but serious. Ice on an AC system indicates restricted airflow (usually a dirty filter or blocked return) or low refrigerant. Either condition stresses the compressor, which is the most expensive component to replace.',
    'Water leaking inside your home around the air handler means your condensate drain is clogged. Normally, moisture removed from the air drips into a drain pan and exits through a condensate line. When that line clogs, water overflows — potentially damaging drywall, ceilings, and flooring.',
    'A sudden spike in your electricity bill during cooling season, with no change in usage patterns, suggests your AC is working harder than it should. This is often an early sign of refrigerant loss, a dirty system, or a failing component that hasn\'t failed completely yet.',
    'If your AC is cycling on and off every few minutes (short-cycling), it\'s not completing full cooling cycles and is wearing out faster than normal. Short-cycling can be caused by an oversized unit, low refrigerant, or electrical problems. Have it diagnosed before it causes compressor failure.',
  ],
  'heat-pump-vs-furnace-nj': [
    'New Jersey\'s climate — cold winters and hot, humid summers — makes the heating system choice more nuanced than in milder climates. Both heat pumps and gas furnaces can keep you comfortable, but the right choice depends on your home, your energy costs, and how you heat.',
    'A gas furnace burns natural gas to generate heat, delivering warm air (typically 120–140°F) through your duct system. It\'s a proven technology that works reliably even in extreme cold, and natural gas prices in NJ are generally lower per BTU than electricity. However, furnaces only provide heating — you still need a separate central AC system for cooling.',
    'A heat pump moves heat rather than generating it, which is why it can be 2–3 times more efficient than a furnace. In heating mode, it extracts heat from outdoor air (even cold air contains heat energy) and moves it inside. In cooling mode, it reverses the process, functioning as an air conditioner. One system handles both heating and cooling.',
    'The efficiency advantage of heat pumps was historically limited in cold climates because older models lost efficiency when outdoor temperatures dropped below 35°F. Modern cold-climate heat pumps have changed this equation significantly. Models from Mitsubishi, Bosch, and others maintain high efficiency down to -13°F — well below any typical NJ winter day.',
    'For most NJ homeowners in newer, well-insulated homes, a cold-climate heat pump paired with electric backup heat offers the best combination of efficiency and operating cost. For older homes with lower insulation levels, or homeowners who prefer the intense heat of a gas furnace on very cold days, a dual-fuel system (heat pump for mild weather, gas furnace for extreme cold) is often the best compromise.',
    'NJ\'s Clean Energy Program offers rebates for heat pump installations, which can significantly reduce upfront costs. The federal Inflation Reduction Act also provides tax credits for heat pump installations through 2032. When evaluating costs, factor these incentives in — they can make a heat pump financially competitive even with a lower-cost furnace.',
    'Call Go Pro Heating & Cooling at 973-938-2217 for a personalized recommendation. We\'ll evaluate your home\'s specific characteristics, current energy costs, and long-term goals to recommend the system that makes the most sense for your situation.',
  ],
  'energy-saving-hvac-tips': [
    'Your HVAC system accounts for 40–60% of your home\'s energy use. The good news: many of the most effective energy-saving measures cost nothing or very little to implement. Here are 10 ways to reduce your HVAC energy bills starting today.',
    'Change your air filter regularly. A dirty filter forces your system to work harder to pull air through, wasting energy and reducing comfort. Check monthly and replace when visibly dirty — typically every 1–3 months depending on pets, allergies, and usage. A clean filter is the single highest-ROI maintenance task for any HVAC system.',
    'Use a programmable or smart thermostat strategically. Setting your thermostat 7–10°F lower for 8 hours per day (while you\'re at work or asleep) can save up to 10% on annual heating and cooling costs. Smart thermostats like the Ecobee and Nest can do this automatically based on your schedule and even your location.',
    'Seal air leaks around windows, doors, and penetrations through walls. Heated or cooled air escaping through gaps forces your system to run longer to maintain temperature. Focus on attic hatches, pipe penetrations, and electrical outlets on exterior walls — these are often overlooked but significant sources of air leakage.',
    'Close blinds and curtains on south and west-facing windows during the day in summer to block solar heat gain. In winter, open them on sunny days to capture passive solar heat. This simple behavioral change can noticeably reduce cooling and heating loads.',
    'Use ceiling fans. In summer, ceiling fans running counterclockwise create a wind-chill effect that lets you raise your thermostat 4°F without losing comfort. In winter, run fans clockwise on low speed to recirculate warm air that pools near the ceiling.',
    'Schedule annual maintenance for your HVAC system. A properly tuned system runs more efficiently — a tune-up often pays for itself in reduced energy costs within one season. Our 21-point tune-up at Go Pro HVAC starts at $89 for Northern NJ homeowners.',
    'Keep outdoor condenser coils clean. A dirty condenser coil can reduce AC efficiency by 30% or more. Keep vegetation trimmed at least 2 feet from the unit, and hose down the coils annually in spring before cooling season.',
    'Ensure vents and registers are unobstructed. Blocked supply or return vents create pressure imbalances that force your system to work harder. Move furniture away from vents and don\'t close registers in unused rooms — contrary to popular belief, closing registers increases pressure and can damage the system.',
    'Consider a whole-home energy audit. A professional energy audit identifies your home\'s specific weak points and prioritizes improvements by return on investment. Many NJ utility companies offer subsidized audits, and the improvements they recommend often pay back in 3–5 years through energy savings.',
  ],
  'when-to-replace-hvac-system': [
    'One of the most common questions we get from Northern NJ homeowners is: should I repair or replace my HVAC system? The answer depends on several factors — and getting it right can mean the difference between spending a few hundred dollars now versus thousands in the next year or two.',
    'Age is the most important factor. A gas furnace has a typical lifespan of 15–20 years. A central AC system typically lasts 12–15 years in NJ\'s climate. Once your system passes these thresholds, the calculus usually favors replacement — not because older systems can\'t be repaired, but because the repair frequency and cost both increase significantly after these ages.',
    'The repair cost rule of thumb: if a repair costs more than 50% of the replacement cost, and the system is over 10 years old, replacement is almost always the better investment. For example, a $1,500 compressor replacement on a 14-year-old AC system doesn\'t make financial sense when a new, more efficient system with a warranty costs $4,000–$6,000.',
    'Increasing repair frequency is a clear signal. One repair every few years is normal maintenance. If you\'re calling for service twice a year, or if you\'ve had major repairs in consecutive seasons, your system is telling you it\'s reached the end of its reliable life.',
    'Declining comfort despite running constantly means your system is losing capacity. If your home struggles to reach set temperature on hot or cold days, or if some rooms are comfortable while others aren\'t, your system may be undersized for current conditions or losing efficiency as components wear.',
    'Surging energy bills with no change in usage are a reliable indicator of declining efficiency. As systems age, efficiency drops — a 15-year-old AC might operate at 50–70% of its original efficiency even if it hasn\'t had a major failure. The increased energy cost often justifies replacement even without a specific breakdown.',
    'If your system uses R-22 refrigerant (common in systems installed before 2010), replacement is worth seriously considering. R-22 was phased out federally and is now extremely expensive — a refrigerant recharge can cost $200 or more per pound. Systems that need R-22 added regularly are poor candidates for continued repair.',
    'Call us at 973-938-2217 for an honest, no-pressure assessment. We\'ll evaluate your current system, explain your options, and give you a transparent comparison of repair vs. replacement costs — including any available rebates or financing that might change the math.',
  ],
  'ductless-mini-split-benefits': [
    'Roughly 40% of New Jersey homes were built before 1970 — many without central ductwork. For decades, homeowners in these homes chose between window AC units, electric baseboard heat, or the significant cost of adding ductwork for central HVAC. Ductless mini-split systems have changed that equation entirely.',
    'A ductless mini-split system consists of an outdoor compressor unit connected to one or more indoor air handlers by small refrigerant lines that run through a 3-inch hole in the wall. There\'s no ductwork required. Each indoor unit has its own thermostat and can maintain a different temperature from other zones in the house.',
    'The efficiency advantage is significant. Mini-splits typically achieve 20–30 SEER ratings (compared to 14–18 SEER for most central AC systems), meaning they use substantially less electricity to produce the same amount of cooling or heating. In older NJ homes with poor insulation, this efficiency advantage is especially valuable because the system can compensate for envelope losses without overworking.',
    'For addition and renovation projects, mini-splits are often the only practical choice. Adding ductwork to an existing addition is typically prohibitively expensive — the ductwork itself can cost more than the HVAC equipment. A mini-split can be installed in a day with minimal structural impact.',
    'Zoned comfort is one of the most underappreciated benefits. With a multi-zone mini-split, you can heat or cool only the rooms that are occupied, and each person can set their preferred temperature independently. For a household with different temperature preferences, this eliminates the thermostat wars.',
    'Modern mini-splits function as heat pumps, providing both heating and cooling. Cold-climate models (Mitsubishi Hyper Heat, Daikin Aurora, and similar products) maintain full heating output down to 5°F and operate effectively down to -13°F — well within any temperature New Jersey experiences. For many NJ homes, a mini-split can be the sole heating and cooling system.',
    'Installation typically takes one day for a single-zone system and one to two days for a multi-zone setup. The indoor unit is mounted high on a wall or in a ceiling cassette configuration, and the refrigerant lines are routed through a small penetration in the exterior wall to the outdoor unit. No major construction required.',
    'Go Pro Heating & Cooling installs and services all major mini-split brands throughout Northern NJ. Call 973-938-2217 for a free in-home consultation — we\'ll assess your space, explain your options, and provide a transparent estimate with no pressure.',
  ],
}
